app = "pluralkit"
kill_signal = "SIGTERM"
kill_timeout = 5

[metrics]
  port = 9091
  path = "/metrics"

[deploy]
  strategy = "bluegreen"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 500
    soft_limit = 400
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443