name: Deploy web proxy to Fly.io

on:
  push:
    branches: [main]
    paths:
      - 'services/web-proxy'

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: (cd services/web-proxy && flyctl deploy)
